### ISSUE TITLE
Enable WAF for the CloudFront distributions

### ISSUE THREAD

**Issue by mfcaro** [cn-terraform/terraform-aws-s3-static-website#10]

**Comment by bendubuisson** [comment]
Any plans to implement this?

**Comment by jnonino** [comment]
Hi @bendubuisson, we didn't have the time to implement this yet. Any contribution is welcome, and we try to review and merge them as quick as possible.

**Comment by bendubuisson** [comment]
Awesome, will work on this asap

**Comment by bendubuisson** [comment]
https://github.com/cn-terraform/terraform-aws-s3-static-website/pull/28
