### ISSUE TITLE
Error: missing provider provider["registry.terraform.io/hashicorp/aws"].main

### ISSUE THREAD

**Issue by fritzalbrecht** [cn-terraform/terraform-aws-s3-static-website#76]
I keep getting this error when applying the plan. Happens after entering the name_prefix and website_domain_name variables.

**Comment by fritzalbrecht** [comment]
Figured it out, I had to add a provider block for each aws alias:

`provider "aws" {
  region = "us-east-1"
  alias = "main"
}

provider "aws" {
  region = "us-east-1"
  alias = "acm_provider"
}`

**Comment by neilfulwiler** [comment]
ran into the same thing, you can just do 
```
{
   aws.main = aws
   aws.acm_manager = aws
}
```
ie telling the module that both of those providers are just aws

**Comment by afreisinger** [comment]
Hi @neilfulwiler where you add

{
   aws.main = aws
   aws.acm_manager = aws
}

I don't understand how to use the module
